travis:
  secure:
    BINSTAR_TOKEN: qVl8olPhPaeq2gnqHz1WUvNgfV4VCSyeWrLPPYt7/ACU1YmWz3h7tbs5NARa/D6xbbpvZoBjkmB3M7oZJbWyMnfbUJt9/813acSLNvB01WzzARrcCMfiRRV4uKnDVnmftnPiPQz61ORw3aksKgWnIYQPB+wBeeoFbwDxfyrH9LqbN7x7lHb57YX49qWl0EoHYc6/4NSQYip6W9JqHNL2PuqPyUQC1dU3UlKbP6W5qKfMsMvJovnjDpTVVpoybrwp22PP2BIDCdT6JfOBHfqOJxWo9+XJcwPerHPTuPlQnQFvVOj8Q4iTbKX7go5Td7X7zc/v8Q1VQpdrUrf/zL4FANIsMuIH7JYhjyAoTLT3S8oBGHZWGxt5RH8zzmPjwgoZ0iGEXyvApSNJe6sil3Odeyg1SIwF283hMzxd+dbs51azciBZHLRboo/wqN6D2spbHb1IhU+w80ZUY/GGKlhhK1hb/PMnueoUOng1fTUNDWLxCHdbPi+aJeVRX4kyw/J+LvWpFEVWs1HTfJ75yn5md9MzqHMHv8IrzzGe/KXaazwz0wkl2nKoiZHvzxAMVawgqlfy2lKbG+n6Z0B2QZn6S6QHrPDZAaF3MxvUcdmJkzHnGLTpgQLdqyAcMWJ9zDzhWqfF/nexIYzVWbpoLhfVkDudkTDoK5e7or2VjtSxB1k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
